import test from 'node:test';
import assert from 'node:assert/strict';
import {parseDoubanEvents,isUpcomingEvent,mergeCityEvents} from '../lib/city-events.mjs';
const now=Date.parse('2026-09-22T12:00:00+08:00');
const fixture=`<div id="db-events-list"><li class="list-entry" itemscope><a href="https://www.douban.com/event/123/"><span itemprop="summary">城市电影放映 &amp; 对谈</span></a><time itemprop="startDate" datetime="2026-09-23T18:00:00"></time><time itemprop="endDate" datetime="2026-09-23T21:00:00"></time><meta itemprop="location" content="杭州 西湖区 某影院"/><li class="fee"><strong>30元起</strong></li></li></div>`;
const parsed=()=>parseDoubanEvents(fixture,{city:'hangzhou',category:'影视',today:'2026-09-22',sourceUrl:'https://www.douban.com/location/hangzhou/events/week-film'});
test('parses actual event fields instead of navigation links',()=>{const [e]=parsed();assert.equal(e.title,'城市电影放映 & 对谈');assert.equal(e.location,'杭州 西湖区 某影院');assert.equal(e.price,'30元起');assert.equal(e.start,'2026-09-23T18:00:00');assert.equal(e.city,'hangzhou');assert.equal(e.category,'影视');assert.equal(isUpcomingEvent(e,now),true)});
test('rejects login pages and expires events in Beijing timezone',()=>{assert.throws(()=>parseDoubanEvents('<h1>login</h1>',{}));const [e]=parsed();assert.equal(isUpcomingEvent({...e,end:'2026-09-22T11:59:00'},now),false);assert.equal(isUpcomingEvent({...e,end:undefined},now),false)});
test('merge never crosses cities and preserves first discovery and last known data',()=>{const [e]=parsed();const old={...e,discoveredAt:'2026-09-20'};const fresh={...e,title:'更新的放映'};const merged=mergeCityEvents([old,{...e,city:'shanghai',url:'https://www.douban.com/event/456/'}],[fresh],'hangzhou',now);assert.equal(merged.length,1);assert.equal(merged[0].discoveredAt,'2026-09-20');assert.equal(merged[0].title,fresh.title);assert.deepEqual(mergeCityEvents([old],[],'hangzhou',now),[old]);assert.equal(mergeCityEvents([old],[],'hangzhou',now+7*86400000).length,0)});
